/**********************************************************************************
*   Class               :       clsTest_EPMS_POPUP                                *
*   Created Date        :       12/04/2016                                        *
*   Description         :       Test Class for EPMS_POPUP                         *
**********************************************************************************/
@isTest
private class clsTest_EPMS_POPUP{
    static testMethod void testEPMS_POPUP() {
        EPMS_POPUP c = new EPMS_POPUP();
        c.Ids='01pp000000091RE';
    }
}