/**********************************************************************************
*   Class               :       clsTest_EPMS_PO_POPUP                             *
*   Created Date        :       17/04/2016                                        *
*   Description         :       Test Class for EPMS_PO_POPUP                      *
**********************************************************************************/
@isTest
private class clsTest_EPMS_PO_POPUP{
    static testMethod void testEPMS_POPUP() {
        EPMS_PO_POPUP c = new EPMS_PO_POPUP();
        c.Ids='01pp000000091RE';
    }
}