/**********************************************************************************
*   Class               :       clsTest_EPMS_FilePOPUP                            *
*   Created Date        :       17/04/2016                                        *
*   Description         :       Test Class for EPMS_FilePOPUP                     *
**********************************************************************************/

@isTest
private class clsTest_EPMS_FilePOPUP{
    static testMethod void testEPMS_POPUP() {
        EPMS_FilePOPUP c = new EPMS_FilePOPUP();
        c.Ids='01pp000000091RE';
    }
}